apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metastore.fullname" . }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>metastore.thrift.uris</name>
        <value>thrift://metastore-thrift.default.svc.cluster.local:9083</value>
        <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:mysql://mysql-cluster-mysql.default.svc.cluster.local:3306/metastore_db?createDatabaseIfNotExist=true</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>com.mysql.cj.jdbc.Driver</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>root</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>mapr</value>
      </property>
    </configuration>