apiVersion: v2
name: hivemetastore
description: A Helm chart for Hive meta store
type: application
version: 0.2.0
appVersion: "2.3"
dependencies:
  - name: common
    repository: "file://../../common/"
    version: 0.1.0
