apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hpe-tenant-service
value: 10000
globalDefault: false
description: "This priority class is used for tenant services like spark history, cli, and livy."
