{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tenant-validator.hpePrefix" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "services/finalizers"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "daemonsets", "replicasets", "statefulsets/finalizers", "deployments/finalizers", "daemonsets/finalizers", "replicasets/finalizers"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete", "patch", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "roles", "clusterrolebindings", "rolebindings"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets", "podsecuritypolicies"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints", "proxy", "limitranges", "componentstatuses", "replicationcontrollers", "bindings"]
    verbs: ["list", "watch"]
  - apiGroups: ["sparkoperator.hpe.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["security.openshift.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["cluster.mapr.com"]
    resources: ["maprclusters", "maprclusters/status", "maprclusters/finalizers"]
    verbs: ["*"]
  - apiGroups: ["mkd.hpe.com"]
    resources: ["clusters", "clusters/status", "clusters/finalizers"]
    verbs: ["*"]
  - apiGroups: ["fabric.hpe.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["mke.hpe.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["hcp.hpe.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs:  ["create", "update", "delete", "get", "patch", "list", "watch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "signers"]
    verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tenant-validator.hpePrefix" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-validator.hpePrefix" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "tenant-validator.hpePrefix" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
