apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "livy-chart.name" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "livy-chart.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "livy-chart.serviceName" . }}
  template:
    metadata:
      {{ if .Values.istio.enable }}
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      {{ end }}
      labels:
      {{ if .Values.istio.enable }}
        sidecar.istio.io/inject: "true"
      {{ end }}
      {{- include "livy-chart.labels" . | nindent 8 }}
      {{- with .Values.customLabels }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      subdomain: livy-svc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- include "common.nodeAffinity.preferred" . | nindent 12 }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- include "common.nodeAffinity.required" . | nindent 12 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- include "common.podAntiAffinity.preferred" (dict "componentName" ( include "livy-chart.name" . ) ) | nindent 12 }}
      tolerations:
      {{- include "common.tolerations" (dict "componentName" ( include "livy-chart.name" . ) "namespace" .Release.Namespace ) | nindent 8 }}
      imagePullSecrets:
        {{- if .Values.createImagetPullSecret }}
        - name: {{ .Values.imagePullSecretsName }}
        {{ else }}
        - name: {{ .Values.defaultPullSecret }}
      {{- end }}
      serviceAccountName: {{ include "livy-chart.serviceAccountName" . }}
      restartPolicy: {{ .Values.restartPolicy }}
      priorityClassName: "hpe-tenant-service"
      initContainers: []
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          {{- include "common.args" . | nindent 12 }}
          command:
          {{- include "common.commands" . | nindent 12 }}
          env:
          {{- include "livy-chart.env" . | nindent 12 }}
          image: "{{ .Values.image.baseRepository }}/{{ .Values.image.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- include "livy-chart.ports" . | nindent 12 }}
          livenessProbe:
          {{- include "common.probe.liveness" . | nindent 12 }}
          readinessProbe:
          {{- include "common.probe.readiness" . | nindent 12 }}
          lifecycle:
          {{- include "common.probe.lifecycle" . | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
          {{- include "common.securityContext" . | nindent 12 }}
          volumeMounts:
          {{- include "livy-chart.volumeMounts" . | nindent 12 }}
      volumes:
      {{- include "livy-chart.volumes" . | nindent 8 }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
  volumeClaimTemplates:
  {{- include "livy-chart.volumeClaimTemplates" . | nindent 4 }}
