apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tenant-validator-mutating-webhook-cfg
  labels:
    app: tenant-validator-app
webhooks:
  - name: tenant-validator.hcp.hpe.com
    failurePolicy: Ignore
    clientConfig:
      service:
        name: tenant-validator-svc
        namespace: hpe-system
        path: /hcp/tenant/v1/mutate
      caBundle: {tenantvalidator-servercert-encoded}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["hcp.hpe.com"]
        apiVersions: ["v1"]
        resources: ["tenants"]
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 20
