apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tenant-validator-svc.hpe-system
spec:
  signerName: kubernetes.io/kubelet-serving
  groups:
    - system:authenticated
  request: {tenant-validator-csr}
  usages:
    - digital signature
    - key encipherment
    - server auth