{{ $componentName := .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: {{ $componentName }}
  namespace: {{ .Values.tenantNameSpace }}
spec:
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
  {{- include "spark-hs-operator-chart.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
    {{ include "spark-hs-operator-chart.labels" (dict "componentName" $componentName "context" $) | nindent 8 }}
    spec:
      subdomain: {{ $componentName }}-svc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{-  include "spark-hs-operator-chart.nodeAffinity.preferred" . | nindent 12 }}
          requiredDuringSchedulingIgnoredDuringExecution:
        {{-  include "spark-hs-operator-chart.nodeAffinity.required" . | nindent 12 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
      {{-  include "spark-hs-operator-chart.podAntiAffinity.preferred" . | nindent 12 }}
      tolerations:
      {{- include "spark-hs-operator-chart.tolerations" . | nindent 8}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.tenantServiceAccount.name }}
      restartPolicy: {{ .Values.restartPolicy }}
      priorityClassName: "hpe-tenant-service"
      initContainers: []
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken  }}
      containers:
        - name: {{ $componentName }}
          {{- with .Values.conatinerConfigs.standardArgs }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.conatinerConfigs.standardCommand }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.conatinerConfigs.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- include "spark-hs-operator-chart.ports" . | nindent 12 }}
          livenessProbe:
          {{- include "spark-hs-operator-chart.probe.liveness" . | nindent 12 }}
          readinessProbe:
          {{- include "spark-hs-operator-chart.probe.readiness" . | nindent 12 }}
          lifecycle:
          {{- include "spark-hs-operator-chart.probe.lifecycle" . | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
          {{- include "spark-hs-operator-chart.securityContext" . | nindent 12 }}
          {{- with .Values.conatinerConfigs.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
  {{- toYaml .Values.podSecurityContext | nindent 8 }}
