apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: autoticket-generator-mutating-webhook-cfg
  labels:
    app: autoticket-generator-app
webhooks:
  - name: autoticket-generator.hcp.hpe.com
    failurePolicy: Fail
    clientConfig:
      service:
        name: autoticket-generator-svc
        namespace: {configure-namepsace}
        path: /sparkapplication/v1beta2/mutate
      caBundle: {autoticket-servercert-encoded}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["sparkoperator.hpe.com"]
        apiVersions: ["v1beta2"]
        resources: ["sparkapplications"]
      - operations: [ "CREATE" ]
        apiGroups: [ "sparkoperator.k8s.io" ]
        apiVersions: [ "v1beta2" ]
        resources: [ "sparkapplications" ]
    timeoutSeconds: 20
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1"]
    namespaceSelector:
      matchLabels:
        hpe.com/namespacetype: Tenant
  - name: scheduled-autoticket-generator.hcp.hpe.com
    failurePolicy: Fail
    clientConfig:
      service:
        name: autoticket-generator-svc
        namespace: {configure-namepsace}
        path: /scheduledsparkapplication/v1beta2/mutate
      caBundle: {autoticket-servercert-encoded}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "sparkoperator.hpe.com" ]
        apiVersions: [ "v1beta2" ]
        resources: [ "scheduledsparkapplications" ]
      - operations: [ "CREATE" ]
        apiGroups: [ "sparkoperator.k8s.io" ]
        apiVersions: [ "v1beta2" ]
        resources: [ "scheduledsparkapplications" ]
    timeoutSeconds: 20
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1"]
    namespaceSelector:
      matchLabels:
        hpe.com/namespacetype: Tenant
