apiVersion: v2
name: hivemeta
description: A Helm chart for Hive meta store
type: application
version: 0.2.0
appVersion: "3.1.3.0"
dependencies:
  - name: common
    repository: "file://../../common/"
    version: 0.1.0
