apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: autoticket-generator-svc.hpe-system
spec:
  signerName: kubernetes.io/kubelet-serving
  groups:
    - system:authenticated
  request: {autoticket-csr-data}
  usages:
    - digital signature
    - key encipherment
    - server auth
